### PR TITLE
Battery energy sensors as total_increasing

### PR DESCRIPTION
**Pull request by GiorgioUghini**
- Renamed "Energy charging capacity" to "Energy charged today"
- Renamed "Energy discharging capacity" to "Energy discharged today"
- Set both sensor to total_increasing

### CODE REVIEW

**Comment by GiorgioUghini** [comment]
Fixes [#51](https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues/51)

**Comment by tijsverkoyen** [comment]
@GiorgioUghini is there a specific reason why you have changed the naming. As I want to keep them aligned with the documentation.

**Comment by GiorgioUghini** [comment]
> @GiorgioUghini is there a specific reason why you have changed the naming. As I want to keep them aligned with the documentation.

I agree with having the labels associated to documentation, however I did change the label referring to the battery energy because it was not only confusing, but also wrong. I don't know if this is an error in Huawei documentation or not, however the situation is:
-> Those sensor display the daily energy used by the battery to recharge itself ("charging capacity") or the energy given by to battery to the house ("discharging capacity").
Now, if I were to read "Battery-1 - Charge Energy" it could be understandable, maybe not the best English but understandable.
But "Charging Capacity" in my opinion is related to a CAPACITY. I.e. my system has a capacity of 15 kWh, but some cloudy days I get a "charging capacity" equal to let's say 2kWh, while other sunny days, it may even exceed 15kWh as I might consume energy while still sunny.
I thought that this would add clearness but feel free to revert back to documentation labels.

**Comment by tijsverkoyen** [comment]
@GiorgioUghini I have reverted the change of the labels. But I also added the documentation in the README: https://github.com/tijsverkoyen/HomeAssistant-FusionSolar#what-does-all-entities-mean

**Pull request merged**
